### ISSUE TITLE
Add methods to control the intake "wrist" with feedback from and encoder.

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#1]
To make sure that our robot does not extend over its frame perimeter, another axis of control has been added to the intake; it moves up and down, constrained to the lift, but also needs to pitch up and down. While we can control this pitch manually that will not be ideal as a mech operator will have to hold it at that position for the entirety of the match. So it will be necessary for us to create a feedback loop that keeps the intake parallel to the ground.

**Comment by mollymaples** [comment]
created different positions for the wrist
