### ISSUE TITLE
Make a getter method to return the current position of the lift.

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#14]
All this method needs to do is get the current setpoint, and return a string of what position the lift is at. For example, if the lift setpoint was at the greatest value, this getter method would return "scale height". We will use this method for feedback on the driver station dashboard.

**Comment by NathanielDiehl** [comment]
compleated

`	public static String getLiftPostion() {
		if(setPoint == distance1) {
			return "intake";
		}else if(setPoint == distance2) {
			return "swich";
		}else if(setPoint == distance3) {
			return "low level";
		}else if(setPoint == distance4){
			return "high level";
		}else {
			return "lifting";
		}
	}`
