### ISSUE TITLE
Constants referenced in the MoveLiftToPosition Command do not exist

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#16]
`protected void initialize() {    	
    	if(_level == 0) {
    		setPoint = Constants.distance1;
    	}else if(_level == 1) {
    		setPoint = Constants.distance2;
    	}else if(_level == 2) {
    		setPoint = Constants.distance3;
    	}else if(_level == 3) {
    		setPoint = Constants.distance4;
    	}
    }`

The names of these constants have changed, please update them.

**Comment by NathanielDiehl** [comment]
fix the constant names

`if(_level == 0) {
    		setPoint = Constants.intake;
    	}else if(_level == 1) {
    		setPoint = Constants.switchPosition;
    	}else if(_level == 2) {
    		setPoint = Constants.lowLevel;
    	}else if(_level == 3) {
    		setPoint = Constants.highLevel;`
