### ISSUE TITLE
Make getter Methods in the intake class that return the current position of the wrist encoder

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#19]
Similar to how we have methods like `Drive.getLeftVelocity()` that would return to us the (double) current velocity of the left side of the robot, we need to implement a method that returns the position of the encoder hooked up to the wrist motor.

**Comment by mollymaples** [comment]
I made a new method that would say what is happening with the wrist.
public static String getWristPosition() {
		if (wristPosition == Constants.wristUp) {
			return "Keeping cube in";
		} else if (wristPosition == Constants.wristLaunch) {
			return "Launch cube upward, at angle";
		} else if (wristPosition == Constants.wristDown) {
			return "Wrist is parallell to the ground";
		} else {
			return "changing position. Or broken";
		}
	}

**Comment by mollymaples** [comment]
Made a wrist encoder and sensor method.
`public static int getWristEncPosition() {
		return RobotMap.wrist.getSelectedSensorPosition(0);`
