### ISSUE TITLE
Implement the disabledInit and disabledPeriodic methods in Robot.java to reset sensors. 

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#23]
Look at the methods [here](http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/IterativeRobotBase.html) that are part of Robot.java's superclass. Implement the disabledPeriodic and disabledInit methods into our Robot.java so that when and/or while the robot is disabled, its sensors (navx, all encoders, maybe solenoids?) are reset to zero.

**Comment by AbbyR2020** [comment]
made methods to reset sensors and made a master resets
