### ISSUE TITLE
Implement a setter method in Intake to set the position of the wrist. 

### ISSUE THREAD

**Issue by AbbyR2020** [FRC-Team-1710/FRC1710-2018#25]
Right now we can set the position of the wrist via the controller, however sometimes we will need to change its position manually. So a new method, `setWristPosition` needs to be created. It takes one parameter which should just be a double value for the different constants containing the encoder position for each possible wrist position.

**Comment by mollymaples** [comment]
stuff happened. I made a setpoint method.
`	public static void setWristPosition(double setPoint) {
		wristSetPoint = setPoint;`
