### ISSUE TITLE
Model the lift class after our intake class so that we have more getter and setter methods.

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#26]
In intake we have methods that set the set point based on controller input. Right now all of that is being handled in Lift.java is the lifting method that does everything. Split those actions up into getter and setter methods. Those could be, but not limited to:
- setLiftPosition()
- manipulateLift()
- manualOverride()

**Comment by mollymaples** [comment]
I organized the methods, over and over.
