### ISSUE TITLE
TurnToAngle needs to slow down as it approaches the goal angle

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#33]
Instead of using a constant value for the speed, make the speed of turning slow down as the angle error decreases.

**Comment by mollymaples** [comment]
I input some math and logic with the goal angle and the current angle.

`if(RobotMap.navx.getAngle() > _angle) {
    		Drive.leftDrive((RobotMap.navx.getAngle() - _angle) * mult);
    		
    	}else if(RobotMap.navx.getAngle() < _angle) {
    		Drive.rightDrive((RobotMap.navx.getAngle() - _angle) * mult);
    		
    	}
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return RobotMap.navx.getAngle() < _goal + 5 || RobotMap.navx.getAngle() > _goal - 5;
