### ISSUE TITLE
Make the lift safer by implementing the hall effect sensors.

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#49]
There are two hall effect sensors on the bot, one at the top and one at the bottom. If the one at the top is triggered the lift should not be able to move up. If the lift at the bottom is triggered, the lift should not be able to move down. If you look at `lift.manipulateLift()` we prevent the lift from smashing but checking the encoder value, that is not always accurate. To utilize these hall effects it will require that you:

- set up [digital inputs](https://wpilib.screenstepslive.com/s/3120/m/7912/l/599687-using-limit-switches-to-control-behavior) in RobotMap
- make getter methods in lift (canLiftMoveUp and canLiftMoveDown) that return the values of the two hall effects
- modify `lift.manipulateLift()` so that, for example, the llift will not be able to move down if canLiftMoveDown returns false.

**Comment by pennbrabec** [comment]
added hall effect senors to stop the lift from breaking at the top and at the botton
