### ISSUE TITLE
Commands for autonomous control need to be created

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#5]
We need to create commands for autonomous control. Those commands include, but are not limited to:

- Drive to position (uses drive train encoders)
- Turn to angle (uses navx)
- Move lift to position (uses lift encoder)
- Pitch intake (uses feedback from encoder on intake "wrist")
- Track cube (uses vision code)

**Comment by NathanielDiehl** [comment]
it did it.

Created all the commands.

Commands need to be tested.
