### ISSUE TITLE
Turn off Limelight LED's in RobotInit

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#7]
`ledEntry.forceSetNumber("ledMode", 0);`

**Comment by pennbrabec** [comment]
added `NetworkTableInstance table = NetworkTableInstance.getDefault();
		NetworkTable tableTwo = table.getTable("limelight");
		NetworkTableEntry ledEntry = tableTwo.getEntry("ledMode");
		ledEntry.forceSetNumber(1);`
