### ISSUE TITLE
Implement a ramp subsystem

### ISSUE THREAD

**Issue by Team1710CTO** [FRC-Team-1710/FRC1710-2018#8]
Just like we have drive, intake, and vision classes we need to make a class for the ramp. All that would entail is two methods: one to actuate the two giant pistons and another to release the ramp from being held inside of the robot. There are 6 pistons that work to manipulate this ramp:

- two "pancake" pistons to hold the ramp inside of the robot.
- two smaller pistons to unfold the ramp
- two giant pistons to lift a robot on the end of the ramp

The pistons all need to work in pairs so one double solenoid object controls each pair. Also they need to actuate in the order listed above with a little bit of delay between each step.

**Comment by pennbrabec** [comment]
added the ramp class and 3 double solenoids to control the ramp deploy
